In [ ]:
a_tensor_initialization

In [1]:
import torch

# torch.Tensor class
t1 = torch.Tensor([1, 2, 3], device='cpu')
print(t1.dtype)   # >>> torch.float32
print(t1.device)  # >>> cpu
print(t1.requires_grad)  # >>> False
print(t1.size())  # torch.Size([3])
print(t1.shape)   # torch.Size([3])

# if you have gpu device
# t1_cuda = t1.to(torch.device('cuda'))
# or you can use shorthand
# t1_cuda = t1.cuda()
t1_cpu = t1.cpu()

print("#" * 50, 1)

# torch.tensor function
t2 = torch.tensor([1, 2, 3], device='cpu')
print(t2.dtype)  # >>> torch.int64
print(t2.device)  # >>> cpu
print(t2.requires_grad)  # >>> False
print(t2.size())  # torch.Size([3])
print(t2.shape)  # torch.Size([3])

# if you have gpu device
# t2_cuda = t2.to(torch.device('cuda'))
# or you can use shorthand
# t2_cuda = t2.cuda()
t2_cpu = t2.cpu()

print("#" * 50, 2)

a1 = torch.tensor(1)			     # shape: torch.Size([]), ndims(=rank): 0
print(a1.shape, a1.ndim)

a2 = torch.tensor([1])		  	     # shape: torch.Size([1]), ndims(=rank): 1
print(a2.shape, a2.ndim)

a3 = torch.tensor([1, 2, 3, 4, 5])   # shape: torch.Size([5]), ndims(=rank): 1
print(a3.shape, a3.ndim)

a4 = torch.tensor([[1], [2], [3], [4], [5]])   # shape: torch.Size([5, 1]), ndims(=rank): 2
print(a4.shape, a4.ndim)

a5 = torch.tensor([                 # shape: torch.Size([3, 2]), ndims(=rank): 2
    [1, 2],
    [3, 4],
    [5, 6]
])
print(a5.shape, a5.ndim)

a6 = torch.tensor([                 # shape: torch.Size([3, 2, 1]), ndims(=rank): 3
    [[1], [2]],
    [[3], [4]],
    [[5], [6]]
])
print(a6.shape, a6.ndim)

a7 = torch.tensor([                 # shape: torch.Size([3, 1, 2, 1]), ndims(=rank): 4
    [[[1], [2]]],
    [[[3], [4]]],
    [[[5], [6]]]
])
print(a7.shape, a7.ndim)

a8 = torch.tensor([                 # shape: torch.Size([3, 1, 2, 3]), ndims(=rank): 4
    [[[1, 2, 3], [2, 3, 4]]],
    [[[3, 1, 1], [4, 4, 5]]],
    [[[5, 6, 2], [6, 3, 1]]]
])
print(a8.shape, a8.ndim)


a9 = torch.tensor([                 # shape: torch.Size([3, 1, 2, 3, 1]), ndims(=rank): 5
    [[[[1], [2], [3]], [[2], [3], [4]]]],
    [[[[3], [1], [1]], [[4], [4], [5]]]],
    [[[[5], [6], [2]], [[6], [3], [1]]]]
])
print(a9.shape, a9.ndim)

a10 = torch.tensor([                 # shape: torch.Size([4, 5]), ndims(=rank): 2
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
])
print(a10.shape, a10.ndim)

a10 = torch.tensor([                 # shape: torch.Size([4, 1, 5]), ndims(=rank): 3
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
])
print(a10.shape, a10.ndim)

a11 = torch.tensor([                 # ValueError: expected sequence of length 3 at dim 3 (got 2)
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
])



torch.float32
cpu
False
torch.Size([3])
torch.Size([3])
################################################## 1
torch.int64
cpu
False
torch.Size([3])
torch.Size([3])
################################################## 2
torch.Size([]) 0
torch.Size([1]) 1
torch.Size([5]) 1
torch.Size([5, 1]) 2
torch.Size([3, 2]) 2
torch.Size([3, 2, 1]) 3
torch.Size([3, 1, 2, 1]) 4
torch.Size([3, 1, 2, 3]) 4
torch.Size([3, 1, 2, 3, 1]) 5
torch.Size([4, 5]) 2
torch.Size([4, 1, 5]) 3


ValueError: expected sequence of length 3 at dim 3 (got 2)

In [ ]:
torch.Tensor : float32로 반환
torch.tensor : int64로 반환

.cpu() : CPU 사용
.cuda() : GPU 사용

a11의 ValueError : 텐서를 생성할 때 각 차원이 동일한 크기여야 함

In [ ]:
b_tensor_initialization_copy

In [2]:
import torch
import numpy as np

l1 = [1, 2, 3]
t1 = torch.Tensor(l1)

l2 = [1, 2, 3]
t2 = torch.tensor(l2)

l3 = [1, 2, 3]
t3 = torch.as_tensor(l3)

l1[0] = 100
l2[0] = 100
l3[0] = 100

print(t1)
print(t2)
print(t3)

print("#" * 100)

l4 = np.array([1, 2, 3])
t4 = torch.Tensor(l4)

l5 = np.array([1, 2, 3])
t5 = torch.tensor(l5)

l6 = np.array([1, 2, 3])
t6 = torch.as_tensor(l6)

l4[0] = 100
l5[0] = 100
l6[0] = 100

print(t4)
print(t5)
print(t6)


tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([1, 2, 3])
####################################################################################################
tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.int32)
tensor([100,   2,   3], dtype=torch.int32)


In [ ]:
torch.Tensor : float32, 원본을 복사하여 생성
torch.tensor : int64, 원본을 복사하여 생성
torch.as_tensor : 원본을 참조하여 생성 -> 원본 변경시 사본(생성한 텐서)도 변경

In [ ]:
c_tensor_initialization_constant_values

In [3]:
import torch

t1 = torch.ones(size=(5,))  # or torch.ones(5)
t1_like = torch.ones_like(input=t1)
print(t1)  # >>> tensor([1., 1., 1., 1., 1.])
print(t1_like)  # >>> tensor([1., 1., 1., 1., 1.])

t2 = torch.zeros(size=(6,))  # or torch.zeros(6)
t2_like = torch.zeros_like(input=t2)
print(t2)  # >>> tensor([0., 0., 0., 0., 0., 0.])
print(t2_like)  # >>> tensor([0., 0., 0., 0., 0., 0.])

t3 = torch.empty(size=(4,))  # or torch.zeros(4)
t3_like = torch.empty_like(input=t3)
print(t3)  # >>> tensor([0., 0., 0., 0.])
print(t3_like)  # >>> tensor([0., 0., 0., 0.])

t4 = torch.eye(n=3)
print(t4)


tensor([1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1.])
tensor([0., 0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0., 0.])
tensor([1., 2., 3., 0.])
tensor([0.5039, 2.0000, 3.0000, 0.0000])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [ ]:
torch.ones() : 모든 값이 1인 텐서
torch.zeros() : 모든 값이 0인 텐서
torch.empty() : 생성 후 값을 초기화 하지 않음
torch.eye() : 단위 행렬(Identity Matrix) 텐서

In [ ]:
d_tensor_initialization_random_values

In [4]:
import torch

t1 = torch.randint(low=10, high=20, size=(1, 2))
print(t1)

t2 = torch.rand(size=(1, 3))
print(t2)

t3 = torch.randn(size=(1, 3))
print(t3)

t4 = torch.normal(mean=10.0, std=1.0, size=(3, 2))
print(t4)

t5 = torch.linspace(start=0.0, end=5.0, steps=3)
print(t5)

t6 = torch.arange(5)
print(t6)

print("#" * 30)

torch.manual_seed(1729)
random1 = torch.rand(2, 3)
print(random1)

random2 = torch.rand(2, 3)
print(random2)

print()

torch.manual_seed(1729)
random3 = torch.rand(2, 3)
print(random3)

random4 = torch.rand(2, 3)
print(random4)


tensor([[15, 11]])
tensor([[0.8942, 0.2568, 0.8947]])
tensor([[0.2049, 0.0069, 1.0144]])
tensor([[10.4026,  9.6601],
        [10.5118, 10.6927],
        [ 9.1550, 10.9367]])
tensor([0.0000, 2.5000, 5.0000])
tensor([0, 1, 2, 3, 4])
##############################
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


In [ ]:
torch.randint() : 무작위 정수값을 가지는 텐서
torch.rand() : 0 ~ 1의 무작위 실수를 가지는 텐서
torch.randn() : 평균 0, 표준편차 1인 정규분포의 실수를 가지는 텐서
torch.normal() : mean(평균), std(표준편차)의 정규분포에서 실수를 가지는 텐서
torch.linspace() : start와 end 사이의 구간을 steps개의 구간으로 나누어 가지는 텐서
torch.arange() : 주어진 범위 내에서 특정 간격으로 값을 가지는 텐서
torch.manual_seed() : 난수의 seed를 설정하여 값을 가지는 텐서, seed값이 같으면 동일한 결과

In [ ]:
e_tensor_type_conversion

In [5]:
import torch

a = torch.ones((2, 3))
print(a.dtype)

b = torch.ones((2, 3), dtype=torch.int16)
print(b)

c = torch.rand((2, 3), dtype=torch.float64) * 20.
print(c)

d = b.to(torch.int32)
print(d)

double_d = torch.ones(10, 2, dtype=torch.double)
short_e = torch.tensor([[1, 2]], dtype=torch.short)

double_d = torch.zeros(10, 2).double()
short_e = torch.ones(10, 2).short()

double_d = torch.zeros(10, 2).to(torch.double)
short_e = torch.ones(10, 2).to(dtype=torch.short)

double_d = torch.zeros(10, 2).type(torch.double)
short_e = torch.ones(10, 2). type(dtype=torch.short)

print(double_d.dtype)
print(short_e.dtype)

double_f = torch.rand(5, dtype=torch.double)
short_g = double_f.to(torch.short)
print((double_f * short_g).dtype)


torch.float32
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[18.0429,  7.2532, 19.6519],
        [10.8626,  2.1505, 19.6913]], dtype=torch.float64)
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)
torch.float64
torch.int16
torch.float64


In [ ]:
torch.to(), torch.type() : 텐서를 지정한 타입으로 변환하여 반환, 원본 텐서를 변경하지 않음
torch.to()와 torch.type() 데이터 타입 변경에 사용할 수 있지만 to()는 디바이스 변경에도 쓸 수 있다고 함 

In [ ]:
f_tensor_operations

In [6]:
import torch

t1 = torch.ones(size=(2, 3))
t2 = torch.ones(size=(2, 3))
t3 = torch.add(t1, t2)
t4 = t1 + t2
print(t3)
print(t4)

print("#" * 30)

t5 = torch.sub(t1, t2)
t6 = t1 - t2
print(t5)
print(t6)

print("#" * 30)

t7 = torch.mul(t1, t2)
t8 = t1 * t2
print(t7)
print(t8)

print("#" * 30)

t9 = torch.div(t1, t2)
t10 = t1 / t2
print(t9)
print(t10)


tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])
##############################
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
##############################
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
##############################
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
torch.add() : 텐서 덧셈
torch.sub() : 텐서 뺄셈
torch.mul() : 텐서 곱셈
torch.div() : 텐서 나눗셈
element-wise하게 연산함

In [ ]:
g_tensor_operations_mm

In [7]:
import torch

t1 = torch.dot(
  torch.tensor([2, 3]), torch.tensor([2, 1])
)
print(t1, t1.size())

t2 = torch.randn(2, 3)
t3 = torch.randn(3, 2)
t4 = torch.mm(t2, t3)
print(t4, t4.size())

t5 = torch.randn(10, 3, 4)
t6 = torch.randn(10, 4, 5)
t7 = torch.bmm(t5, t6)
print(t7.size())


tensor(7) torch.Size([])
tensor([[1.6750, 2.2840],
        [0.0956, 1.0294]]) torch.Size([2, 2])
torch.Size([10, 3, 5])


In [ ]:
torch.dot() : 텐서의 내적 계산
torch.mm() : 텐서의 행렬 곱셈
torch.bmm() : 텐서의 배치 행렬 곱셈

In [ ]:
h_tensor_operations_matmul

In [8]:
import torch

# vector x vector: dot product
t1 = torch.randn(3)
t2 = torch.randn(3)
print(torch.matmul(t1, t2).size())  # torch.Size([])

# matrix x vector: broadcasted dot
t3 = torch.randn(3, 4)
t4 = torch.randn(4)
print(torch.matmul(t3, t4).size())  # torch.Size([3])

# batched matrix x vector: broadcasted dot
t5 = torch.randn(10, 3, 4)
t6 = torch.randn(4)
print(torch.matmul(t5, t6).size())  # torch.Size([10, 3])

# batched matrix x batched matrix: bmm
t7 = torch.randn(10, 3, 4)
t8 = torch.randn(10, 4, 5)
print(torch.matmul(t7, t8).size())  # torch.Size([10, 3, 5])

# batched matrix x matrix: bmm
t9 = torch.randn(10, 3, 4)
t10 = torch.randn(4, 5)
print(torch.matmul(t9, t10).size())  # torch.Size([10, 3, 5])


torch.Size([])
torch.Size([3])
torch.Size([10, 3])
torch.Size([10, 3, 5])
torch.Size([10, 3, 5])


In [ ]:
i_tensor_broadcasting

In [9]:
import torch

t1 = torch.tensor([1.0, 2.0, 3.0])
t2 = 2.0
print(t1 * t2)

print("#" * 50, 1)

t3 = torch.tensor([[0, 1], [2, 4], [10, 10]])
t4 = torch.tensor([4, 5])
print(t3 - t4)

print("#" * 50, 2)

t5 = torch.tensor([[1., 2.], [3., 4.]])
print(t5 + 2.0)  # t5.add(2.0)
print(t5 - 2.0)  # t5.sub(2.0)
print(t5 * 2.0)  # t5.mul(2.0)
print(t5 / 2.0)  # t5.div(2.0)

print("#" * 50, 3)


def normalize(x):
  return x / 255


t6 = torch.randn(3, 28, 28)
print(normalize(t6).size())

print("#" * 50, 4)

t7 = torch.tensor([[1, 2], [0, 3]])  # torch.Size([2, 2])
t8 = torch.tensor([[3, 1]])  # torch.Size([1, 2])
t9 = torch.tensor([[5], [2]])  # torch.Size([2, 1])
t10 = torch.tensor([7])  # torch.Size([1])
print(t7 + t8)   # >>> tensor([[4, 3], [3, 4]])
print(t7 + t9)   # >>> tensor([[6, 7], [2, 5]])
print(t8 + t9)   # >>> tensor([[8, 6], [5, 3]])
print(t7 + t10)  # >>> tensor([[ 8, 9], [ 7, 10]])

print("#" * 50, 5)

t11 = torch.ones(4, 3, 2)
t12 = t11 * torch.rand(3, 2)  # 3rd & 2nd dims identical to t11, dim 0 absent
print(t12.shape)

t13 = torch.ones(4, 3, 2)
t14 = t13 * torch.rand(3, 1)  # 3rd dim = 1, 2nd dim is identical to t13
print(t14.shape)

t15 = torch.ones(4, 3, 2)
t16 = t15 * torch.rand(1, 2)  # 3rd dim is identical to t15, 2nd dim is 1
print(t16.shape)

t17 = torch.ones(5, 3, 4, 1)
t18 = torch.rand(3, 1, 1)  # 2nd dim is identical to t17, 3rd and 4th dims are 1
print((t17 + t18).size())

print("#" * 50, 6)

t19 = torch.empty(5, 1, 4, 1)
t20 = torch.empty(3, 1, 1)
print((t19 + t20).size())  # torch.Size([5, 3, 4, 1])

t21 = torch.empty(1)
t22 = torch.empty(3, 1, 7)
print((t21 + t22).size())  # torch.Size([3, 1, 7])

t23 = torch.ones(3, 3, 3)
t24 = torch.ones(3, 1, 3)
print((t23 + t24).size())  # torch.Size([3, 3, 3])

# t25 = torch.empty(5, 2, 4, 1)
# t26 = torch.empty(3, 1, 1)
# print((t25 + t26).size())
# RuntimeError: The size of tensor a (2) must match
# the size of tensor b (3) at non-singleton dimension 1

print("#" * 50, 7)

t27 = torch.ones(4) * 5
print(t27)  # >>> tensor([ 5, 5, 5, 5])

t28 = torch.pow(t27, 2)
print(t28)  # >>> tensor([ 25, 25, 25, 25])

exp = torch.arange(1., 5.)  # tensor([ 1.,  2.,  3.,  4.])
a = torch.arange(1., 5.)  # tensor([ 1.,  2.,  3.,  4.])
t29 = torch.pow(a, exp)
print(t29)  # >>> tensor([   1.,    4.,   27.,  256.])


tensor([2., 4., 6.])
################################################## 1
tensor([[-4, -4],
        [-2, -1],
        [ 6,  5]])
################################################## 2
tensor([[3., 4.],
        [5., 6.]])
tensor([[-1.,  0.],
        [ 1.,  2.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])
################################################## 3
torch.Size([3, 28, 28])
################################################## 4
tensor([[4, 3],
        [3, 4]])
tensor([[6, 7],
        [2, 5]])
tensor([[8, 6],
        [5, 3]])
tensor([[ 8,  9],
        [ 7, 10]])
################################################## 5
torch.Size([4, 3, 2])
torch.Size([4, 3, 2])
torch.Size([4, 3, 2])
torch.Size([5, 3, 4, 1])
################################################## 6
torch.Size([5, 3, 4, 1])
torch.Size([3, 1, 7])
torch.Size([3, 3, 3])
################################################## 7
tensor([5., 5., 5., 5.])
tensor([25., 25., 25., 25.])
tensor([  1

In [ ]:
j_tensor_indexing_slicing

In [10]:
import torch

x = torch.tensor(
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9],
   [10, 11, 12, 13, 14]]
)

print(x[1])  # >>> tensor([5, 6, 7, 8, 9])
print(x[:, 1])  # >>> tensor([1, 6, 11])
print(x[1, 2])  # >>> tensor(7)
print(x[:, -1])  # >>> tensor([4, 9, 14)

print("#" * 50, 1)

print(x[1:])  # >>> tensor([[ 5,  6,  7,  8,  9], [10, 11, 12, 13, 14]])
print(x[1:, 3:])  # >>> tensor([[ 8,  9], [13, 14]])

print("#" * 50, 2)

y = torch.zeros((6, 6))
y[1:4, 2] = 1
print(y)

print(y[1:4, 1:4])

print("#" * 50, 3)

z = torch.tensor(
  [[1, 2, 3, 4],
   [2, 3, 4, 5],
   [5, 6, 7, 8]]
)
print(z[:2])
print(z[1:, 1:3])
print(z[:, 1:])

z[1:, 1:3] = 0
print(z)


tensor([5, 6, 7, 8, 9])
tensor([ 1,  6, 11])
tensor(7)
tensor([ 4,  9, 14])
################################################## 1
tensor([[ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])
tensor([[ 8,  9],
        [13, 14]])
################################################## 2
tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])
tensor([[0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.]])
################################################## 3
tensor([[1, 2, 3, 4],
        [2, 3, 4, 5]])
tensor([[3, 4],
        [6, 7]])
tensor([[2, 3, 4],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[1, 2, 3, 4],
        [2, 0, 0, 5],
        [5, 0, 0, 8]])


In [ ]:
k_tensor_reshaping

In [11]:
import torch

t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = t1.view(3, 2)  # Shape becomes (3, 2)
t3 = t1.reshape(1, 6)  # Shape becomes (1, 6)
print(t2)
print(t3)

t4 = torch.arange(8).view(2, 4)  # Shape becomes (2, 4)
t5 = torch.arange(6).view(2, 3)  # Shape becomes (2, 3)
print(t4)
print(t5)

print("#" * 50, 1)

# Original tensor with shape (1, 3, 1)
t6 = torch.tensor([[[1], [2], [3]]])

# Remove all dimensions of size 1
t7 = t6.squeeze()  # Shape becomes (3,)

# Remove dimension at position 0
t8 = t6.squeeze(0)  # Shape becomes (3, 1)
print(t7)
print(t8)

print("#" * 50, 2)

# Original tensor with shape (3,)
t9 = torch.tensor([1, 2, 3])

# Add a new dimension at position 1
t10 = t9.unsqueeze(1)  # Shape becomes (3, 1)
print(t10)

t11 = torch.tensor(
  [[1, 2, 3],
   [4, 5, 6]]
)
t12 = t11.unsqueeze(1)  # Shape becomes (2, 1, 3)
print(t12, t12.shape)

print("#" * 50, 3)

# Original tensor with shape (2, 3)
t13 = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Flatten the tensor
t14 = t13.flatten()  # Shape becomes (6,)

print(t14)

# Original tensor with shape (2, 2, 2)
t15 = torch.tensor([[[1, 2],
                     [3, 4]],
                    [[5, 6],
                     [7, 8]]])
t16 = torch.flatten(t15)

t17 = torch.flatten(t15, start_dim=1)

print(t16)
print(t17)

print("#" * 50, 4)

t18 = torch.randn(2, 3, 5)
print(t18.shape)  # >>> torch.Size([2, 3, 5])
print(torch.permute(t18, (2, 0, 1)).size())  # >>> torch.Size([5, 2, 3])

# Original tensor with shape (2, 3)
t19 = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Permute the dimensions
t20 = torch.permute(t19, dims=(0, 1))  # Shape becomes (2, 3) still
t21 = torch.permute(t19, dims=(1, 0))  # Shape becomes (3, 2)
print(t20)
print(t21)

# Transpose the tensor
t22 = torch.transpose(t19, 0, 1)  # Shape becomes (3, 2)

print(t22)

t23 = torch.t(t19)  # Shape becomes (3, 2)

print(t23)


tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
tensor([[0, 1, 2],
        [3, 4, 5]])
################################################## 1
tensor([1, 2, 3])
tensor([[1],
        [2],
        [3]])
################################################## 2
tensor([[1],
        [2],
        [3]])
tensor([[[1, 2, 3]],

        [[4, 5, 6]]]) torch.Size([2, 1, 3])
################################################## 3
tensor([1, 2, 3, 4, 5, 6])
tensor([1, 2, 3, 4, 5, 6, 7, 8])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
################################################## 4
torch.Size([2, 3, 5])
torch.Size([5, 2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [ ]:
l_tensor_concat

In [12]:
import torch

t1 = torch.zeros([2, 1, 3])
t2 = torch.zeros([2, 3, 3])
t3 = torch.zeros([2, 2, 3])

t4 = torch.cat([t1, t2, t3], dim=1)
print(t4.shape)

print("#" * 50, 1)

t5 = torch.arange(0, 3)  # tensor([0, 1, 2])
t6 = torch.arange(3, 8)  # tensor([3, 4, 5, 6, 7])

t7 = torch.cat((t5, t6), dim=0)
print(t7.shape)  # >>> torch.Size([8])
print(t7)  # >>> tensor([0, 1, 2, 3, 4, 5, 6, 7])

print("#" * 50, 2)

t8 = torch.arange(0, 6).reshape(2, 3)  # torch.Size([2, 3])
t9 = torch.arange(6, 12).reshape(2, 3)  # torch.Size([2, 3])

# 2차원 텐서간 병합
t10 = torch.cat((t8, t9), dim=0)
print(t10.size())  # >>> torch.Size([4, 3])
print(t10)
# >>> tensor([[ 0,  1,  2],
#             [ 3,  4,  5],
#             [ 6,  7,  8],
#             [ 9, 10, 11]])

t11 = torch.cat((t8, t9), dim=1)
print(t11.size())  # >>>torch.Size([2, 6])
print(t11)
# >>> tensor([[ 0,  1,  2,  6,  7,  8],
#             [ 3,  4,  5,  9, 10, 11]])

print("#" * 50, 3)

t12 = torch.arange(0, 6).reshape(2, 3)  # torch.Size([2, 3])
t13 = torch.arange(6, 12).reshape(2, 3)  # torch.Size([2, 3])
t14 = torch.arange(12, 18).reshape(2, 3)  # torch.Size([2, 3])

t15 = torch.cat((t12, t13, t14), dim=0)
print(t15.size())  # >>> torch.Size([6, 3])
print(t15)
# >>> tensor([[ 0,  1,  2],
#             [ 3,  4,  5],
#             [ 6,  7,  8],
#             [ 9, 10, 11],
#             [12, 13, 14],
#             [15, 16, 17]])

t16 = torch.cat((t12, t13, t14), dim=1)
print(t16.size())  # >>> torch.Size([2, 9])
print(t16)
# >>> tensor([[ 0,  1,  2,  6,  7,  8, 12, 13, 14],
#             [ 3,  4,  5,  9, 10, 11, 15, 16, 17]])

print("#" * 50, 4)

t17 = torch.arange(0, 6).reshape(1, 2, 3)  # torch.Size([1, 2, 3])
t18 = torch.arange(6, 12).reshape(1, 2, 3)  # torch.Size([1, 2, 3])

t19 = torch.cat((t17, t18), dim=0)
print(t19.size())  # >>> torch.Size([2, 2, 3])
print(t19)
# >>> tensor([[[ 0,  1,  2],
#              [ 3,  4,  5]],
#             [[ 6,  7,  8],
#              [ 9, 10, 11]]])

t20 = torch.cat((t17, t18), dim=1)
print(t20.size())  # >>> torch.Size([1, 4, 3])
print(t20)
# >>> tensor([[[ 0,  1,  2],
#              [ 3,  4,  5],
#              [ 6,  7,  8],
#              [ 9, 10, 11]]])

t21 = torch.cat((t17, t18), dim=2)
print(t21.size())  # >>> torch.Size([1, 2, 6])
print(t21)
# >>> tensor([[[ 0,  1,  2,  6,  7,  8],
#              [ 3,  4,  5,  9, 10, 11]]])


torch.Size([2, 6, 3])
################################################## 1
torch.Size([8])
tensor([0, 1, 2, 3, 4, 5, 6, 7])
################################################## 2
torch.Size([4, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
torch.Size([2, 6])
tensor([[ 0,  1,  2,  6,  7,  8],
        [ 3,  4,  5,  9, 10, 11]])
################################################## 3
torch.Size([6, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])
torch.Size([2, 9])
tensor([[ 0,  1,  2,  6,  7,  8, 12, 13, 14],
        [ 3,  4,  5,  9, 10, 11, 15, 16, 17]])
################################################## 4
torch.Size([2, 2, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 4, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 2, 6])
t

In [ ]:
m_tensor_stacking

In [13]:
import torch

t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = torch.tensor([[7, 8, 9], [10, 11, 12]])

t3 = torch.stack([t1, t2], dim=0)
t4 = torch.cat([t1.unsqueeze(dim=0), t2.unsqueeze(dim=0)], dim=0)
print(t3.shape, t3.equal(t4))

t5 = torch.stack([t1, t2], dim=1)
t6 = torch.cat([t1.unsqueeze(dim=1), t2.unsqueeze(dim=1)], dim=1)
print(t5.shape, t5.equal(t6))

t7 = torch.stack([t1, t2], dim=2)
t8 = torch.cat([t1.unsqueeze(dim=2), t2.unsqueeze(dim=2)], dim=2)
print(t7.shape, t7.equal(t8))

print("#" * 50, 1)

t9 = torch.arange(0, 3)  # tensor([0, 1, 2])
t10 = torch.arange(3, 6)  # tensor([3, 4, 5])

print(t9.size(), t10.size())
# >>> torch.Size([3]) torch.Size([3])

t11 = torch.stack((t9, t10), dim=0)
print(t11.size())  # >>> torch.Size([2,3])
print(t11)
# >>> tensor([[0, 1, 2],
#             [3, 4, 5]])

t12 = torch.cat((t9.unsqueeze(0), t10.unsqueeze(0)), dim=0)
print(t11.equal(t12))
# >>> True

t13 = torch.stack((t9, t10), dim=1)
print(t13.size())  # >>> torch.Size([3,2])
print(t13)
# >>> tensor([[0, 3],
#             [1, 4],
#             [2, 5]])
t14 = torch.cat((t9.unsqueeze(1), t10.unsqueeze(1)), dim=1)
print(t13.equal(t14))
# >>> True


torch.Size([2, 2, 3]) True
torch.Size([2, 2, 3]) True
torch.Size([2, 3, 2]) True
################################################## 1
torch.Size([3]) torch.Size([3])
torch.Size([2, 3])
tensor([[0, 1, 2],
        [3, 4, 5]])
True
torch.Size([3, 2])
tensor([[0, 3],
        [1, 4],
        [2, 5]])
True


In [ ]:
n_tensor_vstack_hstack

In [14]:
import torch

t1 = torch.tensor([1, 2, 3])
t2 = torch.tensor([4, 5, 6])
t3 = torch.vstack((t1, t2))
print(t3)
# >>> tensor([[1, 2, 3],
#             [4, 5, 6]])

t4 = torch.tensor([[1], [2], [3]])
t5 = torch.tensor([[4], [5], [6]])
t6 = torch.vstack((t4, t5))
# >>> tensor([[1],
#             [2],
#             [3],
#             [4],
#             [5],
#             [6]])

t7 = torch.tensor([
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
])
print(t7.shape)
# >>> (2, 2, 3)

t8 = torch.tensor([
  [[13, 14, 15], [16, 17, 18]],
  [[19, 20, 21], [22, 23, 24]]
])
print(t8.shape)
# >>> (2, 2, 3)

t9 = torch.vstack([t7, t8])
print(t9.shape)
# >>> (4, 2, 3)

print(t9)
# >>> tensor([[[ 1,  2,  3],
#              [ 4,  5,  6]],
#             [[ 7,  8,  9],
#              [10, 11, 12]],
#             [[13, 14, 15],
#              [16, 17, 18]],
#             [[19, 20, 21],
#              [22, 23, 24]]])

print("#" * 50, 1)

t10 = torch.tensor([1, 2, 3])
t11 = torch.tensor([4, 5, 6])
t12 = torch.hstack((t10, t11))
print(t12)
# >>> tensor([1, 2, 3, 4, 5, 6])

t13 = torch.tensor([[1], [2], [3]])
t14 = torch.tensor([[4], [5], [6]])
t15 = torch.hstack((t13, t14))
print(t15)
# >>> tensor([[1, 4],
#             [2, 5],
#             [3, 6]])

t16 = torch.tensor([
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
])
print(t16.shape)
# >>> (2, 2, 3)

t17 = torch.tensor([
  [[13, 14, 15], [16, 17, 18]],
  [[19, 20, 21], [22, 23, 24]]
])
print(t17.shape)
# >>> (2, 2, 3)

t18 = torch.hstack([t16, t17])
print(t18.shape)
# >>> (2, 4, 3)

print(t18)
# >>> tensor([[[ 1,  2,  3],
#              [ 4,  5,  6],
#              [13, 14, 15],
#              [16, 17, 18]],
#             [[ 7,  8,  9],
#              [10, 11, 12],
#              [19, 20, 21],
#              [22, 23, 24]]])


tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
torch.Size([4, 2, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24]]])
################################################## 1
tensor([1, 2, 3, 4, 5, 6])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
torch.Size([2, 4, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [13, 14, 15],
         [16, 17, 18]],

        [[ 7,  8,  9],
         [10, 11, 12],
         [19, 20, 21],
         [22, 23, 24]]])


In [ ]:
이번 숙제의 코드를 읽고 실행시키면서 PyTorch의 Tensor에 관한 다양한 함수와 그 사용 방법에 대해 깊이 있게 배울 수 있었습니다.

텐서 생성 및 초기화: 처음에 텐서를 생성하는 다양한 방법과 각 방법의 특징을 살펴보았습니다.
특히, torch.tensor()를 사용한 텐서 생성과 텐서 초기화 함수들(torch.zeros(), torch.ones(), torch.rand() 등)의 
사용법을 익힐 수 있었습니다. 이 부분은 텐서를 효과적으로 초기화하는 데 중요한 기초를 마련해 주었습니다.
자료형 변환: 다음으로, torch.to()와 torch.type()을 사용하여 텐서의 자료형을 변환해 보았습니다. 
이 과정에서 텐서의 자료형을 바꾸는 것이 계산의 정확성 및 성능에 어떻게 영향을 미치는지 이해할 수 있었습니다.
기본 및 고급 연산: 텐서 간의 기본적인 연산부터 시작하여, torch.add(), torch.sub(), torch.mul(), torch.div() 등의 
연산과 함께 고급 수학 연산을 수행하는 방법도 배웠습니다. 
특히, broadcasting을 활용한 연산, 텐서의 형태를 변경하는 연산(reshape, view), 텐서의 합치기 및 쌓기(stack) 
연산에 대한 이해가 깊어졌습니다.

각 코드 조각은 텐서의 기본적인 사용 방법을 익히고, 텐서를 활용한 다양한 연산에 대한 실습을 통해 많은 도움을 주었습니다. 
이러한 연습을 통해 PyTorch의 텐서를 효과적으로 다루는 데 필요한 기초를 탄탄히 할 수 있었습니다.